#ifndef PACKET_TYPE_H
#define PACKET_TYPE_H

enum class PacketType : UInt32 {
	NotifyTerminal,
	DBAccountInfoRequest,
	DBAccountInfoResponse,
	DBCreateCharacterRequest,
	DBCreateCharacterResponse,
	DBDeleteCharacterRequest,
	DBDeleteCharacterResponse,
	DBConnectChannelRequest,
	DBConnectChannelResponse,
	ExitRequest = 100,
	ExitResponse,
	ChannelListRequest,
	ChannelListResponse,
	AccountInfoRequest,
	AccountInfoResponse,
	CreateCharacterRequest,
	CreateCharacterResponse,
	DeleteCharacterRequest,
	DeleteCharacterResponse,
	ConnectChannelRequest,
	ConnectChannelResponse,
	DisconnectChannelRequest,
	DisconnectChannelResponse,
	NotifyConnectPlayer,
	NotifyDisconnectPlayer,
	ChattingRequest,
	ChattingResponse,
	CharacterInfoRequest,
	CharacterInfoResponse,
	NotifyCharacterMovement,
	NotifyCharacterAction,
	ApplyCharacterStatRequest,
	ApplyCharacterStatResponse,
	ResetCharacterStatRequest,
	ResetCharacterStatResponse,
	ApplyCharacterSkillRequest,
	ApplyCharacterSkillResponse,
	ResetCharacterSkillRequest,
	ResetCharacterSkillResponse,
	EquipItemRequest,
	EquipItemResponse,
	DeleteItemRequest,
	DeleteItemResponse,
	TradeItemRequest,
	TradeItemResponse,
	EchantItemRequest,
	EchantItemResponse,
	MonsterItemDropRequest,
	MonsterItemDropResponse,
	BuyItemAtMarketRequest,
	BuyItemAtMarketResponse,
	SellItemAtMarketRequest,
	SellItemAtMarketResponse
};

#endif