#ifndef PACKET_TYPE_H
#define PACKET_TYPE_H

enum class PacketType : UInt32 {
	NotifyTerminal = 0,
	DBSearchAccountRequest,
	DBSearchAccountResponse,
	DBCreateAccountRequest,
	DBCreateAccountResponse,
	DBGetCharacterListRequest,
	DBGetCharacterListResponse,
	DBChangeCharacterOrderRequest,
	DBChangeCharacterOrderResponse,
	DBCreateCharacterRequest,
	DBCreateCharacterResponse,
	DBDeleteCharacterRequest,
	DBDeleteCharacterResponse,
	DBUpdateCharacterStatusRequest,

	NotifyConnectPlayer = 1000,
	NotifyDisconnectPlayer,
	NotifyChat,
	NotifyPlayerMovement,
	NotifyPlayerAction,
	NotifyTakeDamagePlayer,
	NotifyPlayerRevive,
	NotifyPlayerDead,
	NotifyLevelUpPlayer,
	NotifyMonsterMovement,
	NotifyMonsterAction,
	NotifyTakeDamageMonster,
	NotifyRespawnMonster,
	NotifyLoseAggressionMonster,

	ExitRequest = 2000,
	ExitResponse,
	GetChannelListRequest,
	GetChannelListResponse,
	SearchAccountRequest,
	SearchAccountResponse,
	CreateAccountRequest,
	CreateAccountResponse,
	GetCharacterListRequest,
	GetCharacterListResponse,
	ChangeCharacterOrderRequest,
	ChangeCharacterOrderResponse,
	CreateCharacterRequest,
	CreateCharacterResponse,
	DeleteCharacterRequest,
	DeleteCharacterResponse,
	ConnectChannelRequest,
	ConnectChannelResponse,
	DisconnectChannelRequest,
	DisconnectChannelResponse,
	WhisperChat,
	GetMonsterList,
	TakeDamageMonster,
	GainMonsterExp,
	RevivePlayerRequest,
	RevivePlayerResponse,

	ApplyCharacterStatRequest,
	ApplyCharacterStatResponse,
	ResetCharacterStatRequest,
	ResetCharacterStatResponse,
	ApplyCharacterSkillRequest,
	ApplyCharacterSkillResponse,
	ResetCharacterSkillRequest,
	ResetCharacterSkillResponse,
	EquipItemRequest,
	EquipItemResponse,
	DeleteItemRequest,
	DeleteItemResponse,
	TradeItemRequest,
	TradeItemResponse,
	EchantItemRequest,
	EchantItemResponse,
	MonsterItemDropRequest,
	MonsterItemDropResponse,
	BuyItemAtMarketRequest,
	BuyItemAtMarketResponse,
	SellItemAtMarketRequest,
	SellItemAtMarketResponse
};

#endif