using System;

namespace Heroes {
	public enum PacketType : UInt32 {
		ExitRequest = 100,
		ExitResponse,
		AuthLoginRequest,
		AuthLoginResponse,
		AuthRegisterRequest,
		AuthRegisterResponse,
		ChanelStatusRequest,
		ChanelStatusResponse,
		AccountInfoRequest,
		AccountInfoResponse,
		CreateCharacterRequest,
		CreateCharacterResponse,
		DeleteCharacterRequest,
		DeleteCharacterResponse,
		ConnectChanelRequest,
		ConnectChanelResponse,
		DisconnectChanelRequest,
		DisconnectChanelResponse,
		NotifyConnectPlayer,
		NotifyDisconnectPlayer,
		ChattingRequest,
		ChattingResponse,
		CharacterInfoRequest,
		CharacterInfoResponse,
		NotifyCharacterMovement,
		NotifyCharacterAction,
		ApplyCharacterStatRequest,
		ApplyCharacterStatResponse,
		ResetCharacterStatRequest,
		ResetCharacterStatResponse,
		ApplyCharacterSkillRequest,
		ApplyCharacterSkillResponse,
		ResetCharacterSkillRequest,
		ResetCharacterSkillResponse,
		EquipItemRequest,
		EquipItemResponse,
		DeleteItemRequest,
		DeleteItemResponse,
		TradeItemRequest,
		TradeItemResponse,
		EchantItemRequest,
		EchantItemResponse,
		MonsterItemDropRequest,
		MonsterItemDropResponse,
		BuyItemAtMarketRequest,
		BuyItemAtMarketResponse,
		SellItemAtMarketRequest,
		SellItemAtMarketResponse
	}
}