using System;

namespace Heroes {
	public enum PacketType : UInt32 {
        NotifyConnectPlayer = 1000,
        NotifyDisconnectPlayer,
        NotifyChat,
        NotifyPlayerMovement,
        NotifyPlayerAction,
        NotifyTakeDamagePlayer,
        NotifyPlayerRevive,
        NotifyPlayerDead,
        NotifyLevelUpPlayer,
        NotifyMonsterMovement,
        NotifyMonsterAction,
        NotifyTakeDamageMonster,
        NotifyRespawnMonster,
        NotifyLoseAggressionMonster,

        ExitRequest = 2000,
        ExitResponse,
        GetChannelListRequest,
        GetChannelListResponse,
        SearchAccountRequest,
        SearchAccountResponse,
        CreateAccountRequest,
        CreateAccountResponse,
        GetCharacterListRequest,
        GetCharacterListResponse,
        ChangeCharacterOrderRequest,
        ChangeCharacterOrderResponse,
        CreateCharacterRequest,
        CreateCharacterResponse,
        DeleteCharacterRequest,
        DeleteCharacterResponse,
        ConnectChannelRequest,
        ConnectChannelResponse,
        DisconnectChannelRequest,
        DisconnectChannelResponse,
        WhisperChat,
        GetMonsterList,
        TakeDamageMonster,
        GainMonsterExp,
        RevivePlayerRequest,
        RevivePlayerResponse,

        ApplyCharacterStatRequest,
		ApplyCharacterStatResponse,
		ResetCharacterStatRequest,
		ResetCharacterStatResponse,
		ApplyCharacterSkillRequest,
		ApplyCharacterSkillResponse,
		ResetCharacterSkillRequest,
		ResetCharacterSkillResponse,
		EquipItemRequest,
		EquipItemResponse,
		DeleteItemRequest,
		DeleteItemResponse,
		TradeItemRequest,
		TradeItemResponse,
		EchantItemRequest,
		EchantItemResponse,
		MonsterItemDropRequest,
		MonsterItemDropResponse,
		BuyItemAtMarketRequest,
		BuyItemAtMarketResponse,
		SellItemAtMarketRequest,
		SellItemAtMarketResponse
	}
}